algoritmo "Nome do Programa"

var
naluno: caractere
idade: inteiro
curso: caractere
nmaquina: real

inicio
escreval(" Escreva o nome")
leia(naluno)
escreval("Escreva a idade")
leia(idade)
escreval ("Informe o curso")
leia(curso)
escreval("Escreva a Maquina que Voce Opera ")
leia(nmaquina)
escreva("O aluno ",naluno," de idade ",idade," Esta cursando ",curso," Esta utilizando a maquina n",nmaquina)
fimalgoritmo